# -*- coding: utf-8 -*-
"""expense.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_k8lrPL3-Co9qNMU3_9J32t1qArR-9wF
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/expense.csv")

df['Age']=df['Age'].astype(int)

df.head()

df["Bars_Restaurants_Expense"]=""
df["Transport_Car_Expense"]=""
df["Shopping_Expense"]=""
df["Food_Groceries_Expense"]=""
df["Travel_Holidays_Expense"]=""
df["Household_Utilities_Expense"]=""
df["Media_Electronics_Expense"]=""
df["Healthcare_Drug_Stores_Expense"]=""
df["Education_Expense"]=""
df["Insurances_Finances_Expense"]=""
df["Sports_Expense"]=""
df["Leisure_Entertainment_Expense"]=""

df.head()

#-------------------------------------------------------------------------------------------------------------------------------
#bnr

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Bars_Restaurants_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Bars_Restaurants_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Bars_Restaurants_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Bars_Restaurants_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Bars_Restaurants_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Bars_Restaurants_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Bars_Restaurants_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Bars_Restaurants_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Bars_Restaurants_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Bars_Restaurants_Expense']=0.07*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Bars_Restaurants_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Bars_Restaurants_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Bars_Restaurants_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Bars_Restaurants_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Bars_Restaurants_Expense']=0.035*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Bars_Restaurants_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Bars_Restaurants_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Bars_Restaurants_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#transport

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Transport_Car_Expense']=0.07*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Transport_Car_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Transport_Car_Expense']=0.06*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Transport_Car_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Transport_Car_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Transport_Car_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Transport_Car_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Transport_Car_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Transport_Car_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Transport_Car_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Transport_Car_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Transport_Car_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Transport_Car_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Transport_Car_Expense']=0.005*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Transport_Car_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Transport_Car_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Transport_Car_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Transport_Car_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#shopping

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Shopping_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Shopping_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Shopping_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Shopping_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Shopping_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Shopping_Expense']=0.025*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Shopping_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Shopping_Expense']=0.015*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Shopping_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Shopping_Expense']=0.07*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Shopping_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Shopping_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Shopping_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Shopping_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Shopping_Expense']=0.035*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Shopping_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Shopping_Expense']=0.015*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Shopping_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#-------------------------------------------------------------------------------------------------------------------------------
#grocery

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Food_Groceries_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Food_Groceries_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Food_Groceries_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Food_Groceries_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Food_Groceries_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Food_Groceries_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Food_Groceries_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Food_Groceries_Expense']=0.015*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Food_Groceries_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Food_Groceries_Expense']=0.07*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Food_Groceries_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Food_Groceries_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Food_Groceries_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Food_Groceries_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Food_Groceries_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Food_Groceries_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Food_Groceries_Expense']=0.015*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Food_Groceries_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 


#---------------------------------------------------------------------------------------------------------------------------------------------
#travel

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Travel_Holidays_Expense']=0.08*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Travel_Holidays_Expense']=0.06*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Travel_Holidays_Expense']=0.07*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Travel_Holidays_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Travel_Holidays_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Travel_Holidays_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Travel_Holidays_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Travel_Holidays_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Travel_Holidays_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Travel_Holidays_Expense']=0.09*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Travel_Holidays_Expense']=0.07*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Travel_Holidays_Expense']=0.08*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Travel_Holidays_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Travel_Holidays_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Travel_Holidays_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Travel_Holidays_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Travel_Holidays_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Travel_Holidays_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#household

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Household_Utilities_Expense']=0.07*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Household_Utilities_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Household_Utilities_Expense']=0.06*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Household_Utilities_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Household_Utilities_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Household_Utilities_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Household_Utilities_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Household_Utilities_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Household_Utilities_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Household_Utilities_Expense']=0.08*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Household_Utilities_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Household_Utilities_Expense']=0.07*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Household_Utilities_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Household_Utilities_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Household_Utilities_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Household_Utilities_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Household_Utilities_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Household_Utilities_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#-------------------------------------------------------------------------------------------------------------------------------
#media

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Media_Electronics_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Media_Electronics_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Media_Electronics_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Media_Electronics_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Media_Electronics_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Media_Electronics_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Media_Electronics_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Media_Electronics_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Media_Electronics_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Media_Electronics_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Media_Electronics_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Media_Electronics_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Media_Electronics_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Media_Electronics_Expense']=0.005*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Media_Electronics_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Media_Electronics_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Media_Electronics_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Media_Electronics_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#health

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Healthcare_Drug_Stores_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Healthcare_Drug_Stores_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Healthcare_Drug_Stores_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Healthcare_Drug_Stores_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Healthcare_Drug_Stores_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Healthcare_Drug_Stores_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Healthcare_Drug_Stores_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Healthcare_Drug_Stores_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Healthcare_Drug_Stores_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Healthcare_Drug_Stores_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Healthcare_Drug_Stores_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Healthcare_Drug_Stores_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Healthcare_Drug_Stores_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Healthcare_Drug_Stores_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Healthcare_Drug_Stores_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Healthcare_Drug_Stores_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Healthcare_Drug_Stores_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Healthcare_Drug_Stores_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#education
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Education_Expense']=0.06*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Education_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Education_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Education_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Education_Expense']=0.005*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Education_Expense']=0.005*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Education_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Education_Expense']=0.005*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Education_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Education_Expense']=0.08*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Education_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Education_Expense']=0.07*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Education_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Education_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Education_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Education_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Education_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Education_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#-------------------------------------------------------------------------------------------------------------------------------
#insurance

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Insurances_Finances_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Insurances_Finances_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Insurances_Finances_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Insurances_Finances_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Insurances_Finances_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Insurances_Finances_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Insurances_Finances_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Insurances_Finances_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Insurances_Finances_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Insurances_Finances_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Insurances_Finances_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Insurances_Finances_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Insurances_Finances_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Insurances_Finances_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Insurances_Finances_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Insurances_Finances_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Insurances_Finances_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Insurances_Finances_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#sports

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Sports_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Sports_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Sports_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Sports_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Sports_Expense']=0.005*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Sports_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Sports_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Sports_Expense']=0.005*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Sports_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Sports_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Sports_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Sports_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Sports_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Sports_Expense']=0.005*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Sports_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Sports_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Sports_Expense']=0.005*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Sports_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

#---------------------------------------------------------------------------------------------------------------------------------------------
#entertain

df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'Leisure_Entertainment_Expense']=0.05*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Leisure_Entertainment_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Leisure_Entertainment_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'Leisure_Entertainment_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Leisure_Entertainment_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Leisure_Entertainment_Expense']=0.03*df.loc[(df['Age']>=35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Leisure_Entertainment_Expense']=0.04*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Leisure_Entertainment_Expense']=0.01*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Leisure_Entertainment_Expense']=0.02*df.loc[(df['Age']>=35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary'] 

df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'Leisure_Entertainment_Expense']=0.06*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'Leisure_Entertainment_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'Leisure_Entertainment_Expense']=0.05*df.loc[(df['Age']<35)&(df['marital']=='married')&(df['Geography']=='Germany'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'Leisure_Entertainment_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='France'),'EstimatedSalary'] 
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'Leisure_Entertainment_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'Leisure_Entertainment_Expense']=0.03*df.loc[(df['Age']<35)&(df['marital']=='single')&(df['Geography']=='Germany'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'Leisure_Entertainment_Expense']=0.04*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='France'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'Leisure_Entertainment_Expense']=0.01*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Spain'),'EstimatedSalary']
df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'Leisure_Entertainment_Expense']=0.02*df.loc[(df['Age']<35)&(df['marital']=='divorced')&(df['Geography']=='Germany'),'EstimatedSalary']

df.head()

from google.colab import files
df.to_csv('expenses.csv') 
files.download('expenses.csv')

